# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/rgalliera/Documents/marl/forks/selecta/MAgent2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/rgalliera/Documents/marl/forks/selecta/MAgent2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/rgalliera/.local/lib/python3.10/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rgalliera/Documents/marl/forks/selecta/MAgent2/CMakeFiles /home/rgalliera/Documents/marl/forks/selecta/MAgent2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/rgalliera/Documents/marl/forks/selecta/MAgent2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named magent

# Build rule for target.
magent: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 magent
.PHONY : magent

# fast build rule for target.
magent/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/build
.PHONY : magent/fast

#=============================================================================
# Target rules for targets named testlib

# Build rule for target.
testlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 testlib
.PHONY : testlib

# fast build rule for target.
testlib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/build
.PHONY : testlib/fast

src/gridworld/AgentType.o: src/gridworld/AgentType.cc.o
.PHONY : src/gridworld/AgentType.o

# target to build an object file
src/gridworld/AgentType.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/AgentType.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/AgentType.cc.o
.PHONY : src/gridworld/AgentType.cc.o

src/gridworld/AgentType.i: src/gridworld/AgentType.cc.i
.PHONY : src/gridworld/AgentType.i

# target to preprocess a source file
src/gridworld/AgentType.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/AgentType.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/AgentType.cc.i
.PHONY : src/gridworld/AgentType.cc.i

src/gridworld/AgentType.s: src/gridworld/AgentType.cc.s
.PHONY : src/gridworld/AgentType.s

# target to generate assembly for a file
src/gridworld/AgentType.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/AgentType.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/AgentType.cc.s
.PHONY : src/gridworld/AgentType.cc.s

src/gridworld/GridWorld.o: src/gridworld/GridWorld.cc.o
.PHONY : src/gridworld/GridWorld.o

# target to build an object file
src/gridworld/GridWorld.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/GridWorld.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/GridWorld.cc.o
.PHONY : src/gridworld/GridWorld.cc.o

src/gridworld/GridWorld.i: src/gridworld/GridWorld.cc.i
.PHONY : src/gridworld/GridWorld.i

# target to preprocess a source file
src/gridworld/GridWorld.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/GridWorld.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/GridWorld.cc.i
.PHONY : src/gridworld/GridWorld.cc.i

src/gridworld/GridWorld.s: src/gridworld/GridWorld.cc.s
.PHONY : src/gridworld/GridWorld.s

# target to generate assembly for a file
src/gridworld/GridWorld.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/GridWorld.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/GridWorld.cc.s
.PHONY : src/gridworld/GridWorld.cc.s

src/gridworld/Map.o: src/gridworld/Map.cc.o
.PHONY : src/gridworld/Map.o

# target to build an object file
src/gridworld/Map.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/Map.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/Map.cc.o
.PHONY : src/gridworld/Map.cc.o

src/gridworld/Map.i: src/gridworld/Map.cc.i
.PHONY : src/gridworld/Map.i

# target to preprocess a source file
src/gridworld/Map.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/Map.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/Map.cc.i
.PHONY : src/gridworld/Map.cc.i

src/gridworld/Map.s: src/gridworld/Map.cc.s
.PHONY : src/gridworld/Map.s

# target to generate assembly for a file
src/gridworld/Map.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/Map.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/Map.cc.s
.PHONY : src/gridworld/Map.cc.s

src/gridworld/RenderGenerator.o: src/gridworld/RenderGenerator.cc.o
.PHONY : src/gridworld/RenderGenerator.o

# target to build an object file
src/gridworld/RenderGenerator.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/RenderGenerator.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/RenderGenerator.cc.o
.PHONY : src/gridworld/RenderGenerator.cc.o

src/gridworld/RenderGenerator.i: src/gridworld/RenderGenerator.cc.i
.PHONY : src/gridworld/RenderGenerator.i

# target to preprocess a source file
src/gridworld/RenderGenerator.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/RenderGenerator.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/RenderGenerator.cc.i
.PHONY : src/gridworld/RenderGenerator.cc.i

src/gridworld/RenderGenerator.s: src/gridworld/RenderGenerator.cc.s
.PHONY : src/gridworld/RenderGenerator.s

# target to generate assembly for a file
src/gridworld/RenderGenerator.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/RenderGenerator.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/RenderGenerator.cc.s
.PHONY : src/gridworld/RenderGenerator.cc.s

src/gridworld/RewardEngine.o: src/gridworld/RewardEngine.cc.o
.PHONY : src/gridworld/RewardEngine.o

# target to build an object file
src/gridworld/RewardEngine.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/RewardEngine.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/RewardEngine.cc.o
.PHONY : src/gridworld/RewardEngine.cc.o

src/gridworld/RewardEngine.i: src/gridworld/RewardEngine.cc.i
.PHONY : src/gridworld/RewardEngine.i

# target to preprocess a source file
src/gridworld/RewardEngine.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/RewardEngine.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/RewardEngine.cc.i
.PHONY : src/gridworld/RewardEngine.cc.i

src/gridworld/RewardEngine.s: src/gridworld/RewardEngine.cc.s
.PHONY : src/gridworld/RewardEngine.s

# target to generate assembly for a file
src/gridworld/RewardEngine.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/RewardEngine.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/RewardEngine.cc.s
.PHONY : src/gridworld/RewardEngine.cc.s

src/gridworld/test.o: src/gridworld/test.cc.o
.PHONY : src/gridworld/test.o

# target to build an object file
src/gridworld/test.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/test.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/test.cc.o
.PHONY : src/gridworld/test.cc.o

src/gridworld/test.i: src/gridworld/test.cc.i
.PHONY : src/gridworld/test.i

# target to preprocess a source file
src/gridworld/test.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/test.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/test.cc.i
.PHONY : src/gridworld/test.cc.i

src/gridworld/test.s: src/gridworld/test.cc.s
.PHONY : src/gridworld/test.s

# target to generate assembly for a file
src/gridworld/test.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/gridworld/test.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/gridworld/test.cc.s
.PHONY : src/gridworld/test.cc.s

src/runtime_api.o: src/runtime_api.cc.o
.PHONY : src/runtime_api.o

# target to build an object file
src/runtime_api.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/runtime_api.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/runtime_api.cc.o
.PHONY : src/runtime_api.cc.o

src/runtime_api.i: src/runtime_api.cc.i
.PHONY : src/runtime_api.i

# target to preprocess a source file
src/runtime_api.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/runtime_api.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/runtime_api.cc.i
.PHONY : src/runtime_api.cc.i

src/runtime_api.s: src/runtime_api.cc.s
.PHONY : src/runtime_api.s

# target to generate assembly for a file
src/runtime_api.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/runtime_api.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/runtime_api.cc.s
.PHONY : src/runtime_api.cc.s

src/temp_c_booster.o: src/temp_c_booster.cc.o
.PHONY : src/temp_c_booster.o

# target to build an object file
src/temp_c_booster.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/temp_c_booster.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/temp_c_booster.cc.o
.PHONY : src/temp_c_booster.cc.o

src/temp_c_booster.i: src/temp_c_booster.cc.i
.PHONY : src/temp_c_booster.i

# target to preprocess a source file
src/temp_c_booster.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/temp_c_booster.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/temp_c_booster.cc.i
.PHONY : src/temp_c_booster.cc.i

src/temp_c_booster.s: src/temp_c_booster.cc.s
.PHONY : src/temp_c_booster.s

# target to generate assembly for a file
src/temp_c_booster.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/temp_c_booster.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/temp_c_booster.cc.s
.PHONY : src/temp_c_booster.cc.s

src/utility/utility.o: src/utility/utility.cc.o
.PHONY : src/utility/utility.o

# target to build an object file
src/utility/utility.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/utility/utility.cc.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/utility/utility.cc.o
.PHONY : src/utility/utility.cc.o

src/utility/utility.i: src/utility/utility.cc.i
.PHONY : src/utility/utility.i

# target to preprocess a source file
src/utility/utility.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/utility/utility.cc.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/utility/utility.cc.i
.PHONY : src/utility/utility.cc.i

src/utility/utility.s: src/utility/utility.cc.s
.PHONY : src/utility/utility.s

# target to generate assembly for a file
src/utility/utility.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/magent.dir/build.make CMakeFiles/magent.dir/src/utility/utility.cc.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/testlib.dir/build.make CMakeFiles/testlib.dir/src/utility/utility.cc.s
.PHONY : src/utility/utility.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... magent"
	@echo "... testlib"
	@echo "... src/gridworld/AgentType.o"
	@echo "... src/gridworld/AgentType.i"
	@echo "... src/gridworld/AgentType.s"
	@echo "... src/gridworld/GridWorld.o"
	@echo "... src/gridworld/GridWorld.i"
	@echo "... src/gridworld/GridWorld.s"
	@echo "... src/gridworld/Map.o"
	@echo "... src/gridworld/Map.i"
	@echo "... src/gridworld/Map.s"
	@echo "... src/gridworld/RenderGenerator.o"
	@echo "... src/gridworld/RenderGenerator.i"
	@echo "... src/gridworld/RenderGenerator.s"
	@echo "... src/gridworld/RewardEngine.o"
	@echo "... src/gridworld/RewardEngine.i"
	@echo "... src/gridworld/RewardEngine.s"
	@echo "... src/gridworld/test.o"
	@echo "... src/gridworld/test.i"
	@echo "... src/gridworld/test.s"
	@echo "... src/runtime_api.o"
	@echo "... src/runtime_api.i"
	@echo "... src/runtime_api.s"
	@echo "... src/temp_c_booster.o"
	@echo "... src/temp_c_booster.i"
	@echo "... src/temp_c_booster.s"
	@echo "... src/utility/utility.o"
	@echo "... src/utility/utility.i"
	@echo "... src/utility/utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

